### ISSUE TITLE
Visualization with t-SNE

### ISSUE THREAD

**Issue by cbligaard** [howchihlee/ACDC_tutorial#1]
Hi,

I have used ACDC for a couple of projects and I really enjoy the visualization using t-SNE (like you show in the tutorials). However, suddenly the plot comes out very strange (see image). This even happens when I use the exact same code as you posted in your tutorial. 
The only difference I can see is the fact that I use Python 3.6.0 and Anaconda 4.3.1 (x86_64). Do you have any idea on how to solve this issue?

Best regards
Christina

<img width="668" alt="skaermbillede 2017-08-30 kl 13 12 47" src="https://user-images.githubusercontent.com/28345787/29869881-13eafaba-8d85-11e7-8821-f0b369a0af72.png">

**Comment by howchihlee** [comment]
Hi Christina,

Thanks you for your interest in ACDC. The result you got looks like something's wrong with either the tSNE, or the data fed into it. Unfortunately I couldn't reproduce your result so I really don't know what is going on here. I was able to run this ipython notebook in Python 3.6.1 [GCC 5.4.0 20160609] and Anaconda 4.3.25 without any trouble so I guess the environment is not the issue.  
![bmmc](https://user-images.githubusercontent.com/5400340/30610824-71f36fb6-9d4d-11e7-9a23-1bd09a7076ad.png)

Let me know if you are still experiencing problems. I will do my best to help.

Thank!

**Comment by cbligaard** [comment]
Hi again, 
Thank you for your response. I fixed it by switching back to Python 3.5 - but I guess that I would not be a problem in Python 3.6.1 in stead of 3.6.0.
Best regards Christina
